export const STRINGS = {
  SOLICITAR_VIAJE: "Solicitar Viaje",
  BUSCAR_VIAJE: "Buscar viaje",
  MIS_SOLICITUDES: "Mis solicitudes",
  MIS_VIAJES: "Mis viajes",
  ORIGEN: "Origen",
  DESTINO: "Destino",
  UBICACION_SELECCIONADA: "Ubicación seleccionada",
  ERROR_OBTENER_DIRECCION: "Error al obtener la dirección. Intenta de nuevo.",
  CONFIRMAR_CANCELAR_SOLICITUD: "¿Estás seguro de que deseas cancelar esta solicitud de viaje?",
  ERROR_CANCELAR_SOLICITUD: "No se pudo cancelar la solicitud. Por favor, inténtalo de nuevo.",
  SELECCIONAR_ORIGEN_DESTINO: "Por favor selecciona origen y destino en el mapa",
  USUARIO: "Usuario",
  ERROR_SOLICITAR_VIAJE: "Error al solicitar viaje:",
  ERROR_OCURRIDO_SOLICITAR_VIAJE: "Ocurrió un error al solicitar el viaje. Por favor intenta de nuevo.",
  CONFIRMAR_CANCELAR_RESERVA: "¿Estás seguro de que deseas cancelar esta reserva?",
  ERROR_RESERVAR_VIAJE: "Error al reservar viaje:",
  ERROR_OCURRIDO_RESERVAR_VIAJE: "Ocurrió un error al reservar el viaje. Por favor intenta de nuevo.",
  ERROR_CANCELAR_RESERVA: "Error al cancelar reserva:",
  ERROR_OCURRIDO_CANCELAR_RESERVA: "Ocurrió un error al cancelar la reserva. Por favor intenta de nuevo.",
  MIS_SOLICITUDES_DE_VIAJE: "Mis Solicitudes de Viaje",
  NO_TIENES_SOLICITUDES: "No tienes solicitudes de viaje activas.",
  SOLICITAR_UN_VIAJE_AHORA: "Solicitar un viaje ahora",
  PENDIENTE: "Pendiente",
  ACEPTADO: "Aceptado",
  CANCELADO: "Cancelado",
  CANCELANDO: "Cancelando...",
  CANCELAR: "Cancelar",
  INSTRUCCIONES: "Instrucciones:",
  SELECCIONA_ORIGEN_DESTINO_MAPA: "Selecciona origen y destino en el mapa.",
  SELECCIONA_PUNTO_ORIGEN: "Selecciona el punto de origen",
  SELECCIONA_PUNTO_DESTINO: "Selecciona el punto de destino",
  CONFIRMA_SOLICITUD_VIAJE: "Confirma tu solicitud de viaje",
  SELECCIONA_EN_MAPA: "Selecciona en el mapa",
  BUSCANDO_CONDUCTOR: "Buscando conductor...",
  CONDUCTORES_CERCANOS_NOTIFICADOS: "Los conductores cercanos serán notificados de tu solicitud",
  VIAJES_DISPONIBLES: "Viajes disponibles",
  RESENAS: "reseñas)",
  ASIENTO: "asiento",
  ASIENTOS: "s",
  DISPONIBLE: "disp.",
  SIN_CUPOS: "Sin cupos",
  RESERVAR_AHORA: "Reservar ahora",
  SIN_CUPOS_DISPONIBLES: "Sin cupos disponibles",
  NO_TIENES_VIAJES_PROGRAMADOS: "No tienes viajes programados",
  BUSCAR_VIAJES_DISPONIBLES: "Buscar viajes disponibles",
  CONFIRMADO: "Confirmado",
  CONDUCTOR: "Conductor:",
  CANCELAR_RESERVA: "Cancelar reserva",
  ORIGEN_PUNTOS: "Origen: ",
  DESTINO_PUNTOS: "Destino: ",
  ASIENTO_DISPONIBLE: "asiento disponible",
  ASIENTOS_DISPONIBLES: "asientos disponibles",
  VIAJES_ACTIVOS: "Viajes Activos",
  HISTORIAL: "Historial",
  PANEL_DEL_CONDUCTOR: "Panel del Conductor",
  SOLICITUDES_DE_VIAJE: "Solicitudes de viaje",
  NO_HAY_VIAJES_DISPONIBLES: "No hay viajes disponibles en este momento",
  ORIGEN_NO_ESPECIFICADO: "Origen no especificado",
  DESTINO_NO_ESPECIFICADO: "Destino no especificado",
  PASAJERO: "pasajero",
  PASAJEROS: "s",
  PROCESANDO: "Procesando...",
  ACEPTAR_VIAJE: "Aceptar viaje",
  COMPLETADO: "Completado",
  EN_CURSO: "En curso",
  DISPONIBLE_MAYUS: "Disponible",
  COMPLETAR_VIAJE: "Completar viaje",
  NO_TIENES_VIAJES_ACTIVOS: "No tienes viajes activos",
  CREAR_UN_NUEVO_VIAJE: "Crear un nuevo viaje",
  ORIGEN_DESCONOCIDO: "Origen desconocido",
  DESTINO_DESCONOCIDO: "Destino desconocido",
  PASAJERO_NO_ESPECIFICADO: "Pasajero no especificado",
  PRECIO: "Precio: ",
  COMPLETADO_PUNTOS: "Completado: ",
  AUN_NO_TIENES_VIAJES_COMPLETADOS: "Aún no tienes viajes completados en tu historial.",
  CREAR_NUEVO_VIAJE: "Crear nuevo viaje",
  FECHA_Y_HORA_DE_SALIDA: "Fecha y hora de salida",
  ASIENTOS_DISPONIBLES_MAYUS: "Asientos disponibles",
  PRECIO_POR_ASIENTO: "Precio por asiento",
  MODELO_DEL_VEHICULO: "Modelo del vehículo",
  EJ_TOYOTA_COROLLA: "Ej: Toyota Corolla 2020",
  PLACA_DEL_VEHICULO: "Placa del vehículo",
  EJ_ABC123: "Ej: ABC123",
  DURACION_ESTIMADA: "Duración estimada",
  EJ_45_MIN: "Ej: 45 min",
  CREANDO_VIAJE: "Creando viaje...",
  PUBLICAR_VIAJE: "Publicar viaje",
  RECOGER_A: "Recoger a ",
  EL_PASAJERO: "el pasajero",
  UBICACION_DEL_PASAJERO: "Ubicación del pasajero",
  UBICACION_DE_RECOGIDA: "Ubicación de recogida",
  UBICACION_DE_DESTINO: "Ubicación de destino",
  SOLICITUD_DE_VIAJE: "Solicitud de viaje",
  DE: "De: ",
  A: "A: ",
  PASAJEROS_PUNTOS: "Pasajeros: ",
  PRECIO_SUGERIDO: "Precio sugerido",
};